name: "🐛 Bug Report"
description: Found something you weren't expecting? Report it here!
title: "🐛 Bug: <title>"
labels: [
  "Type ◦ Bug"
]
body:
  - type: markdown
    attributes:
      value: |
        1. Please speak `English`.
        2. Make sure you are using the latest version and take a moment to check that your issue hasn't been reported before.
        3. It's really important to provide pertinent details and logs,
           incomplete details will be handled as an invalid report.

        <br />

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a description of your issue here.
    validations:
      required: true

  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps To Reproduce
      description: |
        Describe the steps that need taken by the developer to get the error / issue you're experiencing.
      value: |
        -
        -
        -
        -
    validations:
      required: true

  - type: input
    id: version-thetvapp
    attributes:
      label: "Version - Tag"
      description: |
        Version / tag you are pulling for `thetvapp`
      placeholder: "Ex: 1.0.0"
    validations:
      required: true

  - type: input
    id: version-docker
    attributes:
      label: "Version - Docker"
      description: "Version of docker you are running. Use command `docker --version`."
      placeholder: "Ex: 27.2.0, build 3ab4256"
    validations:
      required: true

  - type: dropdown
    id: image-source
    attributes:
      label: Docker Image Source
      description: |
        Select which docker image you are pulling from
      options:
        - "Github"
        - "Dockerhub"
        - "Custom Built"
    validations:
      required: true

  - type: dropdown
    id: priority-type
    attributes:
      label: Priority
      description: |
        How critical is the issue?
        Do not abuse this. Issues that completely break the utility would be classified as critical
      options:
        - "Low"
        - "Normal"
        - "High"
        - "Urgent"
    validations:
      required: true

  - type: textarea
    id: docker-compose
    attributes:
      label: docker-compose.yml
      description: |
        Copy / paste your `docker-compose.yml` file here

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Paste your docker logs here.
        Paste logs from inside mounted volume `/config/log/*`

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        Please provide screenshots of any errors or the issue you're having.
        Gifs are even better.
