authors:
  Aetherinox:
    name: Aetherinox
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/118329232
    url: https://github.com/Aetherinox
  iflip721:
    name: iflip721
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/28721588
    url: https://github.com/iflip721
  Optx:
    name: Optx
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/32874812
    url: https://github.com/Nvmdfth
